
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://itmicgkwzgzeqdwrisjz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Iml0bWljZ2t3emd6ZXFkd3Jpc2p6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDIzOTM4NTcsImV4cCI6MjA1Nzk2OTg1N30.oJsNH-Ge5x7OXPHeVGli2sYfpTQtwI0_vr2CsGmdhUo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  realtime: {
    params: {
      eventsPerSecond: 50, // Increased for better responsiveness
      maxReconnectAttempts: 50, // More attempts to reconnect
      fastConnectAttempts: 10  // More attempts for initial connection
    }
  },
  auth: {
    persistSession: true,
    autoRefreshToken: true
  },
  global: {
    // Set higher fetch timeout and disable cache for better video streaming
    fetch: (url, options) => {
      return fetch(url, { 
        ...options, 
        timeout: 120000, // Increased timeout to 120 seconds for better video loading
        cache: 'default', // Changed to default for better caching behavior
        keepalive: true, // Keep connection alive
        priority: 'high', // High priority fetch
      });
    }
  }
});

// Configure real-time subscriptions with improved settings
supabase.realtime.setAuth(SUPABASE_PUBLISHABLE_KEY);

// Enable listening to all real-time changes in the database
// with improved connection status handling
supabase.channel('system')
  .on('presence', { event: 'sync' }, () => {
    console.log('Real-time presence event received');
  })
  .subscribe((status) => {
    console.log('Real-time connection status:', status);
  });

// Add empty export to ensure module is recognized
export default {};
