
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bjnxzalqlsgwdbmkakxf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJqbnh6YWxxbHNnd2RibWtha3hmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDA5MDgyNzksImV4cCI6MjA1NjQ4NDI3OX0.aS0aMzS99YjWc9G5zz_YozC6cDg1NkSHSpS8cF77950";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
