
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://itmicgkwzgzeqdwrisjz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Iml0bWljZ2t3emd6ZXFkd3Jpc2p6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDIzOTM4NTcsImV4cCI6MjA1Nzk2OTg1N30.oJsNH-Ge5x7OXPHeVGli2sYfpTQtwI0_vr2CsGmdhUo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
